server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
