eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOST:helloworld}
    non-secure-port: ${EUREKA_INSTANCE_PORT:80}
    prefer-ip-address: false
    instance-id: ${eureka.instance.hostname}:${eureka.instance.non-secure-port}:${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_SERVICE_URL:http://registry/eureka/}
